In [1]:
import numpy as np

In [2]:
a = [[1,2,3],
     [4,5,6],
     [5,6,7]]

In [3]:
a

[[1, 2, 3], [4, 5, 6], [5, 6, 7]]

In [5]:
b = np.array(a)

In [19]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 7]])

In [20]:
b.T

array([[1, 4, 5],
       [2, 5, 6],
       [3, 6, 7]])

In [12]:
c = np.array([[1,2,3],
              [3,4,5],
              [4,5,6]])

In [15]:
c

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [22]:
e = b.dot(c)
e

array([[19, 25, 31],
       [43, 58, 73],
       [51, 69, 87]])

In [25]:
b @ c

array([[19, 25, 31],
       [43, 58, 73],
       [51, 69, 87]])

In [27]:
f = np.where(e < 20, e, 10*e)

In [28]:
f

array([[ 19, 250, 310],
       [430, 580, 730],
       [510, 690, 870]])