In [28]:
import numpy as np

In [29]:
a = np.arange(0,15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
a[2:6]

array([2, 3, 4, 5])

In [31]:
a[1:5] = 50
a

array([ 0, 50, 50, 50, 50,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
b = a[3:8]
b

array([50, 50,  5,  6,  7])

In [33]:
b[:] = 91
b

array([91, 91, 91, 91, 91])

In [34]:
a

array([ 0, 50, 50, 91, 91, 91, 91, 91,  8,  9, 10, 11, 12, 13, 14])

In [35]:
c = a.copy()
c

array([ 0, 50, 50, 91, 91, 91, 91, 91,  8,  9, 10, 11, 12, 13, 14])

In [37]:
a_m  = np.array([[3,4,1], [1,4,5], [6,9,5]])
a_m

array([[3, 4, 1],
       [1, 4, 5],
       [6, 9, 5]])

In [39]:
a_m[0:2,1:]

array([[4, 1],
       [4, 5]])

In [ ]:
# Last column
a_m[:,-1]

array([1, 5, 5])

In [43]:
b = np.zeros((10,10))
b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])